### ISSUE TITLE
How to disable ia_na in dhcpcd?

### ISSUE THREAD

**Issue by frankcrawford** [sshambar/nmutils#13]
Is there any way to disable `ia_na` requests with running `dhcpcd`?

There looks like there may be a mechanism for doing it for `dhclient`, although I haven't tried it, but cannot see any method for `dhcpcd`.

My reason for this is that my router, while it supports DHCPv6 does not seem to allow me to set up a fixed IPv6 address, so I'm currently getting an extra address from the DHCPv6 server.

**Comment by sshambar** [comment]
Sorry for the delay, been on holiday the last week -- just getting back in the game here :)

Well, it's actually quite simple for dhcpcd, but I don't have an easy flag for it atm... basically if you search in 08-ipv6-prefix (around line 3020) you'll see the generated config file template for dhcpcd -- if you just place a "#' in front of the `ia_na ${iaid}` line and down/up the interface, dhcpcd will no longer request an address (note an address will still be applied by auto-configuration if the router has enabled that though)

If that does what you expect, let me know and I'll add a WAN_IANA_DISABLE or similar flag to allow that behavior to be triggered (for both dhclient and dhcpcd).

**Comment by sshambar** [comment]
BTW, you can use `./08-ipv6-prefix status` to check whether the current status of the client...

**Comment by frankcrawford** [comment]
Yep, it is currently shown in `./08-ipv6-prefix status` as in:
```
DBG: COMMAND: status INTERFACE: 
WAN enp15s0 (UP method=ignore dhcp=dhcpcd)
    autoconf: 2401:d002:1707:4100::1/64 (valid 537 pref 537)
       ia_na: 2401:d002:1707:4100:5291:e3ff:fec8:f7f3/128 (valid 5799 pref 2199)
       ia_pd: 2401:d002:1707:41f8::/62 (valid 5799 pref 2199)
         DNS: fdd2:7aad:d478:1::1
      Search: 
  Default gateway: fe80::464e:6dff:fedf:2f00
  Assigning source-routes
  LAN enp16s0 (UP)
    assigned: 2401:d002:1707:41f8::1/64 (valid 5799 pref 2199)
```

I've commented out `ia_na ${iaid}` now and will see what happens on my next reboot (later today after some patching).

**Comment by frankcrawford** [comment]
An interesting result, certainly disabling `ia_na ${iaid}` stopped it from getting or setting a DHCPv6 IP, but `./08-ipv6-prefix status` still shows it, i.e. after the reboot:
```
DBG: COMMAND: status INTERFACE: 
WAN enp15s0 (UP method=ignore dhcp=dhcpcd)
    autoconf: 2401:d002:1707:4100::1/64 (valid 545 pref 545)
       ia_na: 2401:d002:1707:4100:5291:e3ff:fec8:f7f3/128 (valid 7063 pref 3463)
       ia_pd: 2401:d002:1707:41f8::/62 (valid 7063 pref 3463)
         DNS: fdd2:7aad:d478:1::1
      Search: 
  Default gateway: fe80::464e:6dff:fedf:2f00
  Assigning source-routes
  LAN enp16s0 (UP)
    assigned: 2401:d002:1707:41f8::1/64 (valid 7063 pref 3463)
```
